#!/bin/sh
#
# Simple Redis init.d script conceived to work on Linux systems
# as it does use of the /proc filesystem.
#chkconfig: - 85 15

SENTINELPORT=26379
EXEC=/usr/local/bin/redis-sentinel
CLIEXEC=/usr/local/bin/redis-cli

PIDFILE=/var/run/redis-sentinel.pid
CONF="/etc/redis/sentinel.conf"

case "$1" in
    start)
        if [ -f $PIDFILE ]
        then
                echo "$PIDFILE exists, process is already running or crashed"
        else
                echo "Starting Redis-Sentinel server..."
                $EXEC $CONF
        fi
        ;;
    stop)
        if [ ! -f $PIDFILE ]
        then
                echo "$PIDFILE does not exist, process is not running"
        else
                PID=$(cat $PIDFILE)
                echo "Stopping ..."
                $CLIEXEC -p $SENTINELPORT shutdown
                while [ -x /proc/${PID} ]
                do
                    echo "Waiting for Redis-Sentinel to shutdown ..."
                    sleep 1
                done
                echo "Redis-Sentinel stopped"
        fi
        ;;
    restart)
        if [ ! -f $PIDFILE ]
        then
                echo "$PIDFILE does not exist, process is not running"
        else
                PID=$(cat $PIDFILE)
                echo "Stopping ..."
                $CLIEXEC -p $SENTINELPORT shutdown
                while [ -x /proc/${PID} ]
                do
                    echo "Waiting for Redis-Sentinel to shutdown ..."
                    sleep 1
                done
                echo "Redis-Sentinel stopped"
        fi
        if [ -f $PIDFILE ]
        then
                echo "$PIDFILE exists, process is already running or crashed"
                else
                echo "Starting Redis-Sentinel server..."
                $EXEC $CONF
        fi
        ;;
    status)
        if [ -f $PIDFILE ]
        then
                echo "Running"
        else
                echo "Stopped"
        fi
        ;;

    *)
        echo "Please use start or stop as first argument"
        ;;
esac
